print("----------------------------------------")
print("             HELLO APP                  ")
print("----------------------------------------")
print()
user_name = input("What is your name?")
print("Hi "+user_name)
